name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2
            - name: Update Package Version
              run: |
                  git config --global user.name 'os-jsplopes'
                  git config --global user.email 'julio.lopes@outsystems.com'
                  npm version patch
                  git push --tags origin HEAD:master
