name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2
            - name: Set User
              run: |
                  git config --global user.name 'os-jsplopes'
                  git config --global user.email 'julio.lopes@outsystems.com'
            - name: Version
              run: npm version patch
            - name: Push
              run: git push --tags origin HEAD:master
