name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Install package dependencies
              run: npm install
            - name: Build package
              run: npm run build
            - name: Sync Branch
              run: |
                  git add .
                  git commit -m "update version"
              if: git status --porcelain != null
            - name: Update package version
              run: |
                  git config --global user.name 'os-jsplopes'
                  git config --global user.email 'julio.lopes@outsystems.com'
                  npm version patch
                  git push --tags origin HEAD:master
            - name: Create .npmrc
              run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
            - name: Publish package to github
              run: npm publish --tag master
