name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout master branch
              uses: actions/checkout@v2
            - name: Version
              run: npm version patch
            - name: Commit
              run: git commit -m "update version"
            - name: Push
              run: git push
