name: Pull Request

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout work branch
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Build package
              run: npm run build
            - name: Test package
              run: npm test
